import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const router = useRouter();
  const onGotoProductDetail = () => {
    router.push({
      pathname: "/product/[detailId]",
      query: {
        detailId: 100,
      }
    })
  }
  const onGotoProductByCate = () => {
    router.push({
      pathname: "/categories/[categoryId]/posts/[postId]",
      query: {
        categoryId: 10,
        postId: 100
      }
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/about" >
          <a>About</a>
        </Link>
        <Link href="/product" >
          <a>List Product</a>
        </Link>
        <button onClick={onGotoProductDetail}>
          Go to product detail
        </button>
        <button
          onClick={onGotoProductByCate}
        >
          Go to product by cate
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
